

GET http://localhost:4000/api/users HTTP/1.14



###

POST http://localhost:4000/api/users HTTP/1.14 
Content-Type: application/json

{
    "email": "test@test.com",
    "username":  "test",
    "password":  "password",
    "name" :     "John Doe",
    "role":      "USER"

}


### 
POST http://localhost:4000/login
Content-Type: application/json

{
    "email":"test@test.com",
    "password":"password"
}